command_timeout = 1000

format = """\
$status$username$hostname$directory\
$git_branch$git_status\
\n[ ](none) """

continuation_prompt = "[ ](none) "

[status]
disabled = false
format = '$symbol'
success_symbol = '[▐](fg:green)[ ](fg:green inverted)'
symbol = '[▐](fg:red)[ ](fg:red inverted)'

[username]
disabled = false
format = '[ $user]($style)'
show_always = true
style_root = 'bg:black fg:bright-white'
style_user = 'bg:black fg:white'

[hostname]
disabled = false
format = '[│](fg:black inverted)[$hostname]($style)[▌](fg:black)'
ssh_only = false
style = 'bg:black fg:white'

[directory]
format = '[▐](fg:blue)[ ](fg:blue inverted)[ $path]($style)[▌](fg:black)'
style = 'bg:black fg:white'
truncate_to_repo = false
truncation_length = 3
truncation_symbol = '…/'

[git_branch]
format = "$symbol[ $branch]($style)"
style = 'bg:black fg:white'
symbol = '[▐](fg:cyan)[ ](fg:cyan inverted)'
truncation_length = 10

[git_status]
ahead = ' $count'
behind = ' $count'
diverged = ' $ahead_count $behind_count'

untracked = '[│](fg:black inverted)[U](bg:black fg:green)$count'
modified = '[│](fg:black inverted)[M](bg:black fg:yellow)$count'
deleted = '[│](fg:black inverted)[D](bg:black fg:red)$count'
renamed = '[│](fg:black inverted)[R](bg:black fg:green)$count'

conflicted = '[│](fg:black inverted) $count'
stashed = '[│](fg:black inverted) $count'
staged = '[│](fg:black inverted) $count'

style = 'bg:black fg:white'
format = """\
([│](fg:black inverted)[$ahead_behind]($style))\
([$all_status]($style))[▌](fg:black)"""
